import Context from './components/Context'
import BtmNavi from './components/common/BtmNavi'
import Header from './components/common/Header'
import './globals.scss'
import './reset.scss'

export const metadata = {
	// title: 'Create Next App',
	// description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<title>JEJEPICK</title>
				<link href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/variable/pretendardvariable.css" rel="stylesheet" type="text/css" />
			</head>
			<body>
				<div className='jejepick'>
					<Context>
						<Header />
						<main id='main' className='on'>
							{children}
						</main>
						<BtmNavi />
					</Context>
				</div>
			</body>
		</html>
	)
}
